### ISSUE TITLE
Build Error on libraries/chain/controller.cpp

### ISSUE THREAD

**Issue by coosar** [infiniteXLabs/default-template#2]
Project/libraries/chain/controller.cpp:115:34: error: cannot call member function â€void eosio::chain::controller_impl::on_irreversible(const block_state_ptr&)â€ without object
                                  on_irreversible(b);
                                  ^
libraries/chain/CMakeFiles/eosio_chain.dir/build.make:230: recipe for target 'libraries/chain/CMakeFiles/eosio_chain.dir/controller.cpp.o' failed

See also https://github.com/EOSIO/eos/issues/3246

**Comment by opcheese** [comment]
I had the same problem. Fixed it with -DCMAKE_CXX_COMPILER=/usr/bin/clang++-4.0 -DCMAKE_CC_COMPILER=/usr/bin/clang-4.0
